import { Nunito, Nunito_Sans } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
